name: 'Damm DevOps - Gitflow pull request restriction'
description: 'Gitflow pull request restriction'

outputs:
  pull_request_allowed:
    description: 'Boolean output indicating if pull request target and source branch is allowed.'
    value: ${{ steps.run-script.outputs.pull_request_allowed }}

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: '12'
    - run: export DEFAULT_BRANCH_NAME=${{ github.event.repository.default_branch }} && export SOURCE_BRANCH_NAME=${{ github.head_ref }} && export TARGET_BRANCH_NAME=${{ github.base_ref }} && export GITHUB_TOKEN=${{ github.token }} && cd ${{ github.action_path }} && npm install && node dist/app.js
      shell: bash
      id: run-script

branding:
  icon: 'alert-triangle'
  color: 'gray-dark'
